# It is also called a cluster id sometimes.
# If you have different set of servers and you want to have different death message channel for each server,
# you can set the server-group to the server name.
server-group: default

# Redis configuration
redis:
  host: localhost
  port: 6379
  password: ""

# Death Messages
messages:
  PLAYER_KILL:
    default:
      - "&c{player} &e was killed by &a{killer}&r 😵"
    with_weapon:
      - "&c{player} &e was killed by &a{killer} &e using &r{weapon}&r 🔪"
  ENTITY_ATTACK:
    default:
      - "&c{player} &e was killed by &a{mob}&r 💀"
  PROJECTILE:
    default:
      - "&c{player} &e was shot to death by a projectile&r 🏹"
  SUFFOCATION:
    default:
      - "&c{player} &e suffocated to death&r 😵"
  FALL:
    default:
      - "&c{player} &e fell to death&r 🕳️"
  FIRE:
    default:
      - "&c{player} &e was burnt to death&r 🔥"
  FIRE_TICK:
    default:
      - "&c{player} &e was burnt to death&r 🔥"
  MELTING:
    default:
      - "&c{player} &e melted&r 🌞"
  LAVA:
    default:
      - "&c{player} &e was burnt by lava&r 🌋"
  DROWNING:
    default:
      - "&c{player} &e drowned&r 🌊"
  BLOCK_EXPLOSION:
    default:
      - "&c{player} &e was blown up by an explosion&r 💣"
  ENTITY_EXPLOSION:
    default:
      - "&c{player} &e was blown up by an explosion&r 💣"
  VOID:
    default:
      - "&c{player} &e fell out of the world&r 🕳️"
  LIGHTNING:
    default:
      - "&c{player} &e was struck by lightning&r ⚡"
  SUICIDE:
    default:
      - "&c{player} &e committed suicide&r 😔"
  STARVATION:
    default:
      - "&c{player} &e starved to death&r 🍽️"
  POISON:
    default:
      - "&c{player} &e was poisoned to death&r ☠️"
  MAGIC:
    default:
      - "&c{player} &e was killed by magic&r ✨"
  WITHER:
    default:
      - "&c{player} &e withered away&r 💀"
  FALLING_BLOCK:
    default:
      - "&c{player} &e was squashed by a falling block&r 🧱"
  THORNS:
    default:
      - "&c{player} &e was killed by thorns&r 🌵"
  UNKNOWN:
    default:
      - "&c{player} &e died for unknown reasons&r ❓"

