commands:
  PLAYER_KILL:
    default:
      - "say &c{player} &e被 &a{killer} &e擊殺了 😵"
    with_weapon:
      - "say &c{player} &e被 &a{killer} &e使用 &r{weapon} &e擊殺了 🔪"
  ENTITY_ATTACK:
    default:
      - "say &c{player} &e被 &a{mob} &e攻擊而死 💀"
  PROJECTILE:
    default:
      - "say &c{player} &e被飛射物擊中身亡 🏹"
  SUFFOCATION:
    default:
      - "say &c{player} &e窒息而亡 😵"
  FALL:
    default:
      - "say &c{player} &e墜落身亡 🕳️"
  FIRE:
    default:
      - "say &c{player} &e被火燒死了 🔥"
  FIRE_TICK:
    default:
      - "say &c{player} &e被火燒死了 🔥"
  MELTING:
    default:
      - "say &c{player} &e融化了 🌞"
  LAVA:
    default:
      - "say &c{player} &e被熔岩燒死了 🌋"
  DROWNING:
    default:
      - "say &c{player} &e溺水而亡 🌊"
  BLOCK_EXPLOSION:
    default:
      - "say &c{player} &e被爆炸炸死了 💣"
  ENTITY_EXPLOSION:
    default:
      - "say &c{player} &e被爆炸炸死了 💣"
  VOID:
    default:
      - "say &c{player} &e掉出世界外了 🕳️"
  LIGHTNING:
    default:
      - "say &c{player} &e被閃電擊中了 ⚡"
  SUICIDE:
    default:
      - "say &c{player} &e自殺了 😔"
  STARVATION:
    default:
      - "say &c{player} &e餓死了 🍽️"
  POISON:
    default:
      - "say &c{player} &e被毒死了 ☠️"
  MAGIC:
    default:
      - "say &c{player} &e被魔法殺死了 ✨"
  WITHER:
    default:
      - "say &c{player} &e凋零而亡 💀"
  FALLING_BLOCK:
    default:
      - "say &c{player} &e被落下的方塊壓死了 🧱"
  THORNS:
    default:
      - "say &c{player} &e被荊棘刺死了 🌵"
  UNKNOWN:
    default:
      - "say &c{player} &e因未知原因死亡 ❓"
