name: SyncDeathMessages
version: '${project.version}'
main: org.me.syncdeathmessages.SyncDeathMessages
api-version: 1.19
author: kit8379
commands:
  sdmreload:
    description: Reloads the plugin
    usage: /<command>
    permission: syncdeathmessages.admin